name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 Features'
    labels: 
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

replacers:
  - search: '/([A-Z][A-Z0-9]+)-([0-9]+)/gi'
    replace: '[$1-$2](https://somejiralink.attlasian.net/$1-$2)'
version-resolver:
  default: minor
