name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 Features'
    labels: 
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

replacers:
  - search: '/TP-(\d+)/gi'
    replace: '[TP-$1](https://somejiralink.attlasian.net/TP-$1)'

exclude-labels:
  - 'skip-changelog'