name: Release

on:
  release:
    types: ["prereleased"]
    
jobs:
  jira-release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Update JIRA release notes
          uses: extenda/actions/jira-releasenotes@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: TP

        - name: Create JIRA release
          uses: extenda/actions/jira-release@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: '${{ secrets.JIRA_PROJECT_KEY }}'
            version: ${{ steps.outputs.semver.release-version }}