name: Release

on:
  release:
    types: ["prereleased"]
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        uses: extenda/actions/conventional-release@master
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  jira-release:
      runs-on: ubuntu-latest
      needs: release
      steps:
        - uses: actions/checkout@v2

        - uses: extenda/actions/conventional-version@master
          id: semver
          with:
            version-suffix: -SNAPSHOT

        - name: Print outputs from semver
          run: |
            echo ${{ steps.semver.outputs.version }}
            echo ${{ steps.semver.outputs.branch-name }}
            echo ${{ steps.semver.outputs.branch-name-friendly }}
            echo ${{ steps.semver.outputs.is-prerelease }}
            echo ${{ steps.semver.outputs.short-sha }}
            echo ${{ steps.semver.outputs.composed-version-string }}

        - name: Update JIRA release notes
          uses: extenda/actions/jira-releasenotes@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: TP

        - name: Create JIRA release
          uses: extenda/actions/jira-release@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: '${{ secrets.JIRA_PROJECT_KEY }}'
            version: ${{ steps.outputs.semver.release-version }}