name: Release

on:
  release:
    types: ["prereleased"]
    
jobs:
  jira-release:
      runs-on: ubuntu-latest
      steps:
        - name: Event Body
          run: echo "${{ github.event.release.body }}"
        - name: Dump env
          run: env | sort
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Parse Jira Keys from Commit
          id: jira_keys
          if: always()
          uses: zdmano/jira-extract-issue-keys@master
          with:
            is-pull-request: false
            parse-all-commits: false
            commit-message: ${{ github.event.release.body }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Set fix version
          run: |
            IFS=',' read -ra KEYS <<< "${{ steps.jira_keys.outputs.jira-keys }}"; for id in "${KEYS[@]}"; do curl --globoff -v -X POST ${{JIRA_VERSION_WEBHOOK}}?issue=$id; done
            
