name: Release

on:
  release:
    types: ["prereleased"]
    
jobs:
  jira-release:
      runs-on: ubuntu-latest
      steps:
        - name: Event Body
          run: echo "${{ github.event.body }}"
        - name: Dump env
          run: env | sort
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Parse Jira Keys from Commit
          id: jira_keys
          if: always()
          uses: zdmano/jira-extract-issue-keys@master
          with:
            is-pull-request: false
            parse-all-commits: false
            parse-event-body: '${{ github.event.body }}'
            commit-message: ${{ github.event.body }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create JIRA release
          uses: extenda/actions/jira-release@master
          env:
            JIRA_USERNAME: '${{ secrets.JIRA_USERNAME }}'
            JIRA_PASSWORD: '${{ secrets.JIRA_PASSWORD }}'
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: '${{ secrets.JIRA_PROJECT_KEY }}'
            version: '1.0.0-stage'