name: Release

on:
  release:
    types: ["prereleased"]
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        uses: extenda/actions/conventional-release@master
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  jira-release:
      runs-on: ubuntu-latest
      needs: release
      steps:
        - uses: actions/checkout@v2

        - uses: extenda/actions/conventional-version@master
          id: semver

        - name: Update JIRA release notes
          uses: extenda/actions/jira-releasenotes@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: TP

        - name: Create JIRA release
          uses: extenda/actions/jira-release@master
          with:
            jira-host: '${{ secrets.JIRA_URL }}'
            jira-project: '${{ secrets.JIRA_PROJECT_KEY }}'
            version: ${{ steps.outputs.semver.release-version }}