name: E2E

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
    secrets:
      TOKEN: 
        required: false
concurrency: 
  group: ci-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    name: my-job
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2

      - run : |
          echo 'printing envs'
          env
      - run : |
          echo 'printing super secret'
          echo "$SUPER_SECRET_ENV"