name: E2E

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
    secrets:
      TOKEN: 
        required: false
concurrency: 
  group: ci-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    name: my-job
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: set env
        environment: development
        if: ${{inputs.ENVIRONMENT}}
        environment: ${{ inputs.ENVIRONMENT }}

      - uses: actions/checkout@v2

      - run : |
          echo 'printing envs'
          env
      - run : |
          echo 'printing inputs'
          ${{inputs.ENVIRONMENT}}