name: Test Branch Condition

on: [push]

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX  

jobs:
  release_drafter:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.release_drafter.outputs.id }}
      name: ${{ steps.release_drafter.outputs.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@master
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs: [release_drafter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Ouput info
        run: echo ${{needs.release_drafter.outputs.id}} ${{needs.release_drafter.outputs.name}} 
      - name: Create JIRA release
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        uses: zdmano/jira-release@main
        with:
          jira-host: ${{ secrets.JIRA_URL }}
          jira-project: TEST
          version: ${{ needs.release_drafter.outputs.name }}
          jira-keys: TEST-1, TEST-2, TEST-3

