name: Test Branch Condition

on: [push]

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX  

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: release-drafter/release-drafter@master
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Ouput info
        run: echo ${{steps.release_drafter.outputs.id}} ${{steps.release_drafter.outputs.name}} 
      - name: Create JIRA release
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        uses: extenda/actions/jira-release@v0
        with:
          jira-host: ${{ secrets.JIRA_URL }}
          jira-project: TEST
          version: ${{ steps.release_drafter.outputs.name }}

