name: Test Branch Condition

on: [push]

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX  

jobs:
  test_on_push:
    uses: zdmano/test-jira/.github/workflows/reusable.yml@main
    with:
      ENVIRONMENT: $GITHUB_ENV

