name: Test Branch Condition

on: [push]

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          latest: true
        run: echo ${{latest_release}}


