name: Test Branch Condition

on: [push]

jobs:
  test_on_push:
    runs-on: ubuntu-18.04
    steps:
      - name: Test on master
        if: github.ref == 'refs/heads/main'
        run: echo "Master"

      - name: Test on branch
        if: github.ref != 'refs/heads/main'
        run: echo "Not master"