name: Test Branch Condition

on: [push]

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag_name: v9.1.0
      - name: Ouput info
        run: echo ${{steps.latest_release.outputs.id}} ${{steps.latest_release.outputs.name}} ${{steps.latest_release.id}} ${{steps.latest_release.draft}} ${{steps.latest_release.created_at}}
      - name: Create JIRA release
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        uses: extenda/actions/jira-release@v0
        with:
          jira-host: ${{ secrets.JIRA_URL }}
          jira-project: TEST
          version: ${{ steps.latest_release.outputs.name }}

